// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event-packet-inclusions/event/{event_id}": {
            "get": {
                "description": "Retrieves all event packets that include a specific event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packet-inclusions"
                ],
                "summary": "Get event packets by event ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of event packets",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/httpdto.HttpResponseEventPacket"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid event ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/event-packet-inclusions/event/{event_id}/packet/{packet_id}": {
            "post": {
                "description": "Adds an event to an event packet. Validates that the event has enough seats to meet the packet's allocated_seats requirement.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packet-inclusions"
                ],
                "summary": "Create an event packet inclusion",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "packet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Inclusion data",
                        "name": "inclusion",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpCreateEventPacketInclusion"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Inclusion created successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacketInclusion"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event or packet not found (foreign key error)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Inclusion already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes an event from an event packet by deleting the inclusion relationship",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packet-inclusions"
                ],
                "summary": "Delete an event packet inclusion",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "packet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Inclusion deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacketInclusion"
                        }
                    },
                    "400": {
                        "description": "Invalid event or packet ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Inclusion not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates an existing inclusion relationship between an event and a packet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packet-inclusions"
                ],
                "summary": "Update an event packet inclusion",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "event_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "packet_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpUpdateEventPacketInclusion"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Inclusion updated successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacketInclusion"
                        }
                    },
                    "400": {
                        "description": "Invalid IDs, request body, or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Inclusion not found or foreign key error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/event-packet-inclusions/packet/{packet_id}": {
            "get": {
                "description": "Retrieves all events that are included in a specific event packet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packet-inclusions"
                ],
                "summary": "Get events by packet ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "packet_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of events",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/httpdto.HttpResponseEvent"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid packet ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/event-packets": {
            "post": {
                "description": "Creates a new event packet. Event packets can include multiple events and have allocated seats that must not exceed the minimum seats of included events.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packets"
                ],
                "summary": "Create a new event packet",
                "parameters": [
                    {
                        "description": "Event packet to create",
                        "name": "event_packet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpCreateEventPacket"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Event packet created successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacket"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Event packet already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/event-packets/{id}": {
            "get": {
                "description": "Retrieves a single event packet using its unique integer ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packets"
                ],
                "summary": "Get an event packet by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested event packet",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacket"
                        }
                    },
                    "400": {
                        "description": "Invalid event packet ID format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event packet not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an event packet by its ID and returns the deleted event packet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packets"
                ],
                "summary": "Delete an event packet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event packet deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacket"
                        }
                    },
                    "400": {
                        "description": "Invalid event packet ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event packet not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates an existing event packet by its ID. Validates that allocated_seats does not exceed minimum seats of included events.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event-packets"
                ],
                "summary": "Update an event packet",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event Packet ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpUpdateEventPacket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event packet updated successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventPacket"
                        }
                    },
                    "400": {
                        "description": "Invalid event packet ID format, request body, or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event packet not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Name already taken",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Retrieves a list of events with optional filters, sorting, and pagination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Filter and list events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by location (partial match)",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by description (partial match)",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minimum seats",
                        "name": "min_seats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum seats",
                        "name": "max_seats",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (e.g., name_asc, seats_desc)",
                        "name": "order_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "A list of events",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEventList"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new event to the system.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create a new event",
                "parameters": [
                    {
                        "description": "Event to create",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpCreateEvent"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Event created successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEvent"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Event already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Retrieves a single event using its unique integer ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Get an event by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested event",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEvent"
                        }
                    },
                    "400": {
                        "description": "Invalid event ID format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an event by its ID and returns the deleted event.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Delete an event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEvent"
                        }
                    },
                    "400": {
                        "description": "Invalid event ID format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates an existing event by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Update an event",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpUpdateEvent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event updated successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseEvent"
                        }
                    },
                    "400": {
                        "description": "Invalid event ID format or request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Name already taken",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tickets": {
            "post": {
                "description": "Creates a new ticket for either an event or an event packet. The ticket code is automatically generated as a UUID. Validates seat availability before creation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Create a new ticket",
                "parameters": [
                    {
                        "description": "Ticket to create (must specify either event_id or packet_id, not both)",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpCreateTicket"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ticket created successfully with auto-generated code",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseTicket"
                        }
                    },
                    "400": {
                        "description": "Invalid request format, validation error, or no seats available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Ticket already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error or unexpected error occurred",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tickets/{code}": {
            "get": {
                "description": "Retrieves a single ticket using its unique UUID code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Get a ticket by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket Code (UUID)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The requested ticket",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseTicket"
                        }
                    },
                    "400": {
                        "description": "Invalid ticket code format or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a ticket by its code and returns the deleted ticket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Delete a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket Code (UUID)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseTicket"
                        }
                    },
                    "400": {
                        "description": "Invalid ticket code format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates an existing ticket by its code. Validates seat availability when reassigning to a different event or packet.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tickets"
                ],
                "summary": "Update a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket Code (UUID)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update (event_id or packet_id)",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpUpdateTicket"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ticket updated successfully",
                        "schema": {
                            "$ref": "#/definitions/httpdto.HttpResponseTicket"
                        }
                    },
                    "400": {
                        "description": "Invalid ticket code format, request body, or validation error (e.g., no seats available)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Ticket not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "An unexpected error occurred",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.Link": {
            "type": "object",
            "properties": {
                "href": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "httpdto.HttpCreateEvent": {
            "type": "object",
            "required": [
                "id_owner",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "seats": {
                    "type": "integer"
                }
            }
        },
        "httpdto.HttpCreateEventPacket": {
            "type": "object",
            "required": [
                "id_owner",
                "name"
            ],
            "properties": {
                "allocated_seats": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "httpdto.HttpCreateEventPacketInclusion": {
            "type": "object"
        },
        "httpdto.HttpCreateTicket": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "integer"
                },
                "packet_id": {
                    "type": "integer"
                }
            }
        },
        "httpdto.HttpResponseEvent": {
            "type": "object",
            "properties": {
                "event": {
                    "$ref": "#/definitions/httpdto.httpResponseEvent"
                }
            }
        },
        "httpdto.HttpResponseEventList": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpdto.httpResponseEvent"
                    }
                }
            }
        },
        "httpdto.HttpResponseEventPacket": {
            "type": "object",
            "properties": {
                "event_packet": {
                    "$ref": "#/definitions/httpdto.httpResponseEventPacket"
                }
            }
        },
        "httpdto.HttpResponseEventPacketInclusion": {
            "type": "object",
            "properties": {
                "id_event": {
                    "type": "integer"
                },
                "id_packet": {
                    "type": "integer"
                }
            }
        },
        "httpdto.HttpResponseTicket": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "event_id": {
                    "type": "integer"
                },
                "packet_id": {
                    "type": "integer"
                }
            }
        },
        "httpdto.HttpUpdateEvent": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "seats": {
                    "type": "integer"
                }
            }
        },
        "httpdto.HttpUpdateEventPacket": {
            "type": "object",
            "properties": {
                "allocated_seats": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "httpdto.HttpUpdateEventPacketInclusion": {
            "type": "object"
        },
        "httpdto.HttpUpdateTicket": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "integer"
                },
                "packet_id": {
                    "type": "integer"
                }
            }
        },
        "httpdto.httpResponseEvent": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/http.Link"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "seats": {
                    "type": "integer"
                }
            }
        },
        "httpdto.httpResponseEventPacket": {
            "type": "object",
            "properties": {
                "allocated_seats": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_owner": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/event-manager",
	Schemes:          []string{},
	Title:            "Event Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
