// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/idm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationshipUpdateOperation int32

const (
	RelationshipUpdateOperation_OPERATION_UNSPECIFIED RelationshipUpdateOperation = 0
	RelationshipUpdateOperation_OPERATION_CREATE      RelationshipUpdateOperation = 1
	RelationshipUpdateOperation_OPERATION_DELETE      RelationshipUpdateOperation = 2
)

// Enum value maps for RelationshipUpdateOperation.
var (
	RelationshipUpdateOperation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_CREATE",
		2: "OPERATION_DELETE",
	}
	RelationshipUpdateOperation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_CREATE":      1,
		"OPERATION_DELETE":      2,
	}
)

func (x RelationshipUpdateOperation) Enum() *RelationshipUpdateOperation {
	p := new(RelationshipUpdateOperation)
	*p = x
	return p
}

func (x RelationshipUpdateOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationshipUpdateOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_idm_proto_enumTypes[0].Descriptor()
}

func (RelationshipUpdateOperation) Type() protoreflect.EnumType {
	return &file_proto_idm_proto_enumTypes[0]
}

func (x RelationshipUpdateOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationshipUpdateOperation.Descriptor instead.
func (RelationshipUpdateOperation) EnumDescriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // User email address
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // User password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_idm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT token in Base64Url format with claims: iss, sub, exp, jti, role
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User ID (corresponds to 'sub' claim in JWT)
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                   // User role (corresponds to 'role' claim in JWT)
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`                 // User email address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_idm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *LoginResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token to verify
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenRequest) Reset() {
	*x = VerifyTokenRequest{}
	mi := &file_proto_idm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenRequest) ProtoMessage() {}

func (x *VerifyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenRequest.ProtoReflect.Descriptor instead.
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                          // false if expired or blacklisted, true if valid
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                           // User email address
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                       // Contains reason if invalid (expired, blacklisted, corrupted)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // User ID extracted from token's 'sub' claim (clear text)
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`                             // Role extracted from token's 'role' claim (clear text)
	Issuer        string                 `protobuf:"bytes,6,opt,name=issuer,proto3" json:"issuer,omitempty"`                         // Issuer extracted from token's 'iss' claim
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Expiration timestamp from token's 'exp' claim
	Expired       bool                   `protobuf:"varint,8,opt,name=expired,proto3" json:"expired,omitempty"`                      // true if token has expired
	Blacklisted   bool                   `protobuf:"varint,9,opt,name=blacklisted,proto3" json:"blacklisted,omitempty"`              // true if token is in blacklist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTokenResponse) Reset() {
	*x = VerifyTokenResponse{}
	mi := &file_proto_idm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTokenResponse) ProtoMessage() {}

func (x *VerifyTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTokenResponse.ProtoReflect.Descriptor instead.
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTokenResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyTokenResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *VerifyTokenResponse) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *VerifyTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *VerifyTokenResponse) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

func (x *VerifyTokenResponse) GetBlacklisted() bool {
	if x != nil {
		return x.Blacklisted
	}
	return false
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // JWT token to revoke/destroy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_proto_idm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Always true (validation processing completed successfully)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // Success message or reason for revocation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_proto_idm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ObjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectType    string                 `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_proto_idm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{6}
}

func (x *ObjectReference) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ObjectReference) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

type SubjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectType   string                 `protobuf:"bytes,1,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	SubjectId     string                 `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Relation      *string                `protobuf:"bytes,3,opt,name=relation,proto3,oneof" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectReference) Reset() {
	*x = SubjectReference{}
	mi := &file_proto_idm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectReference) ProtoMessage() {}

func (x *SubjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectReference.ProtoReflect.Descriptor instead.
func (*SubjectReference) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{7}
}

func (x *SubjectReference) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *SubjectReference) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *SubjectReference) GetRelation() string {
	if x != nil && x.Relation != nil {
		return *x.Relation
	}
	return ""
}

type RelationshipTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Relation      string                 `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipTuple) Reset() {
	*x = RelationshipTuple{}
	mi := &file_proto_idm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipTuple) ProtoMessage() {}

func (x *RelationshipTuple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipTuple.ProtoReflect.Descriptor instead.
func (*RelationshipTuple) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{8}
}

func (x *RelationshipTuple) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *RelationshipTuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationshipTuple) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ObjectReference       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Permission    string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	Subject       *SubjectReference      `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_proto_idm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPermissionRequest) GetResource() *ObjectReference {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CheckPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *CheckPermissionRequest) GetSubject() *SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permitted     bool                   `protobuf:"varint,1,opt,name=permitted,proto3" json:"permitted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_proto_idm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{10}
}

func (x *CheckPermissionResponse) GetPermitted() bool {
	if x != nil {
		return x.Permitted
	}
	return false
}

func (x *CheckPermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RelationshipUpdate struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Operation     RelationshipUpdateOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=idm.RelationshipUpdateOperation" json:"operation,omitempty"`
	Relationship  *RelationshipTuple          `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipUpdate) Reset() {
	*x = RelationshipUpdate{}
	mi := &file_proto_idm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipUpdate) ProtoMessage() {}

func (x *RelationshipUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipUpdate.ProtoReflect.Descriptor instead.
func (*RelationshipUpdate) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{11}
}

func (x *RelationshipUpdate) GetOperation() RelationshipUpdateOperation {
	if x != nil {
		return x.Operation
	}
	return RelationshipUpdateOperation_OPERATION_UNSPECIFIED
}

func (x *RelationshipUpdate) GetRelationship() *RelationshipTuple {
	if x != nil {
		return x.Relationship
	}
	return nil
}

type WriteRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       []*RelationshipUpdate  `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRelationshipsRequest) Reset() {
	*x = WriteRelationshipsRequest{}
	mi := &file_proto_idm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipsRequest) ProtoMessage() {}

func (x *WriteRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*WriteRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{12}
}

func (x *WriteRelationshipsRequest) GetUpdates() []*RelationshipUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type WriteRelationshipsResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RelationshipsWritten int32                  `protobuf:"varint,3,opt,name=relationships_written,json=relationshipsWritten,proto3" json:"relationships_written,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WriteRelationshipsResponse) Reset() {
	*x = WriteRelationshipsResponse{}
	mi := &file_proto_idm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRelationshipsResponse) ProtoMessage() {}

func (x *WriteRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*WriteRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{13}
}

func (x *WriteRelationshipsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteRelationshipsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WriteRelationshipsResponse) GetRelationshipsWritten() int32 {
	if x != nil {
		return x.RelationshipsWritten
	}
	return 0
}

type RelationshipFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceFilter *ObjectReference       `protobuf:"bytes,1,opt,name=resource_filter,json=resourceFilter,proto3,oneof" json:"resource_filter,omitempty"`
	RelationFilter *string                `protobuf:"bytes,2,opt,name=relation_filter,json=relationFilter,proto3,oneof" json:"relation_filter,omitempty"`
	SubjectFilter  *SubjectReference      `protobuf:"bytes,3,opt,name=subject_filter,json=subjectFilter,proto3,oneof" json:"subject_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelationshipFilter) Reset() {
	*x = RelationshipFilter{}
	mi := &file_proto_idm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipFilter) ProtoMessage() {}

func (x *RelationshipFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipFilter.ProtoReflect.Descriptor instead.
func (*RelationshipFilter) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{14}
}

func (x *RelationshipFilter) GetResourceFilter() *ObjectReference {
	if x != nil {
		return x.ResourceFilter
	}
	return nil
}

func (x *RelationshipFilter) GetRelationFilter() string {
	if x != nil && x.RelationFilter != nil {
		return *x.RelationFilter
	}
	return ""
}

func (x *RelationshipFilter) GetSubjectFilter() *SubjectReference {
	if x != nil {
		return x.SubjectFilter
	}
	return nil
}

type ReadRelationshipsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *RelationshipFilter    `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         *int32                 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRelationshipsRequest) Reset() {
	*x = ReadRelationshipsRequest{}
	mi := &file_proto_idm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRelationshipsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRelationshipsRequest) ProtoMessage() {}

func (x *ReadRelationshipsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRelationshipsRequest.ProtoReflect.Descriptor instead.
func (*ReadRelationshipsRequest) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{15}
}

func (x *ReadRelationshipsRequest) GetFilter() *RelationshipFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadRelationshipsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ReadRelationshipsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*RelationshipTuple   `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRelationshipsResponse) Reset() {
	*x = ReadRelationshipsResponse{}
	mi := &file_proto_idm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRelationshipsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRelationshipsResponse) ProtoMessage() {}

func (x *ReadRelationshipsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRelationshipsResponse.ProtoReflect.Descriptor instead.
func (*ReadRelationshipsResponse) Descriptor() ([]byte, []int) {
	return file_proto_idm_proto_rawDescGZIP(), []int{16}
}

func (x *ReadRelationshipsResponse) GetRelationships() []*RelationshipTuple {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *ReadRelationshipsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_proto_idm_proto protoreflect.FileDescriptor

const file_proto_idm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/idm.proto\x12\x03idm\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9c\x01\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"*\n" +
	"\x12VerifyTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xfb\x01\n" +
	"\x13VerifyTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06issuer\x18\x06 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12\x18\n" +
	"\aexpired\x18\b \x01(\bR\aexpired\x12 \n" +
	"\vblacklisted\x18\t \x01(\bR\vblacklisted\"*\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x13RevokeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x0fObjectReference\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1b\n" +
	"\tobject_id\x18\x02 \x01(\tR\bobjectId\"\x82\x01\n" +
	"\x10SubjectReference\x12!\n" +
	"\fsubject_type\x18\x01 \x01(\tR\vsubjectType\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tH\x00R\brelation\x88\x01\x01B\v\n" +
	"\t_relation\"\x92\x01\n" +
	"\x11RelationshipTuple\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.idm.ObjectReferenceR\bresource\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12/\n" +
	"\asubject\x18\x03 \x01(\v2\x15.idm.SubjectReferenceR\asubject\"\x9b\x01\n" +
	"\x16CheckPermissionRequest\x120\n" +
	"\bresource\x18\x01 \x01(\v2\x14.idm.ObjectReferenceR\bresource\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12/\n" +
	"\asubject\x18\x03 \x01(\v2\x15.idm.SubjectReferenceR\asubject\"Q\n" +
	"\x17CheckPermissionResponse\x12\x1c\n" +
	"\tpermitted\x18\x01 \x01(\bR\tpermitted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x90\x01\n" +
	"\x12RelationshipUpdate\x12>\n" +
	"\toperation\x18\x01 \x01(\x0e2 .idm.RelationshipUpdateOperationR\toperation\x12:\n" +
	"\frelationship\x18\x02 \x01(\v2\x16.idm.RelationshipTupleR\frelationship\"N\n" +
	"\x19WriteRelationshipsRequest\x121\n" +
	"\aupdates\x18\x01 \x03(\v2\x17.idm.RelationshipUpdateR\aupdates\"\x85\x01\n" +
	"\x1aWriteRelationshipsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x15relationships_written\x18\x03 \x01(\x05R\x14relationshipsWritten\"\x84\x02\n" +
	"\x12RelationshipFilter\x12B\n" +
	"\x0fresource_filter\x18\x01 \x01(\v2\x14.idm.ObjectReferenceH\x00R\x0eresourceFilter\x88\x01\x01\x12,\n" +
	"\x0frelation_filter\x18\x02 \x01(\tH\x01R\x0erelationFilter\x88\x01\x01\x12A\n" +
	"\x0esubject_filter\x18\x03 \x01(\v2\x15.idm.SubjectReferenceH\x02R\rsubjectFilter\x88\x01\x01B\x12\n" +
	"\x10_resource_filterB\x12\n" +
	"\x10_relation_filterB\x11\n" +
	"\x0f_subject_filter\"p\n" +
	"\x18ReadRelationshipsRequest\x12/\n" +
	"\x06filter\x18\x01 \x01(\v2\x17.idm.RelationshipFilterR\x06filter\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"z\n" +
	"\x19ReadRelationshipsResponse\x12<\n" +
	"\rrelationships\x18\x01 \x03(\v2\x16.idm.RelationshipTupleR\rrelationships\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount*d\n" +
	"\x1bRelationshipUpdateOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPERATION_CREATE\x10\x01\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x022\xbe\x03\n" +
	"\x0fIdentityService\x12.\n" +
	"\x05Login\x12\x11.idm.LoginRequest\x1a\x12.idm.LoginResponse\x12@\n" +
	"\vVerifyToken\x12\x17.idm.VerifyTokenRequest\x1a\x18.idm.VerifyTokenResponse\x12@\n" +
	"\vRevokeToken\x12\x17.idm.RevokeTokenRequest\x1a\x18.idm.RevokeTokenResponse\x12L\n" +
	"\x0fCheckPermission\x12\x1b.idm.CheckPermissionRequest\x1a\x1c.idm.CheckPermissionResponse\x12U\n" +
	"\x12WriteRelationships\x12\x1e.idm.WriteRelationshipsRequest\x1a\x1f.idm.WriteRelationshipsResponse\x12R\n" +
	"\x11ReadRelationships\x12\x1d.idm.ReadRelationshipsRequest\x1a\x1e.idm.ReadRelationshipsResponseB\x12Z\x10idmService/protob\x06proto3"

var (
	file_proto_idm_proto_rawDescOnce sync.Once
	file_proto_idm_proto_rawDescData []byte
)

func file_proto_idm_proto_rawDescGZIP() []byte {
	file_proto_idm_proto_rawDescOnce.Do(func() {
		file_proto_idm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_idm_proto_rawDesc), len(file_proto_idm_proto_rawDesc)))
	})
	return file_proto_idm_proto_rawDescData
}

var file_proto_idm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_idm_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_idm_proto_goTypes = []any{
	(RelationshipUpdateOperation)(0),   // 0: idm.RelationshipUpdateOperation
	(*LoginRequest)(nil),               // 1: idm.LoginRequest
	(*LoginResponse)(nil),              // 2: idm.LoginResponse
	(*VerifyTokenRequest)(nil),         // 3: idm.VerifyTokenRequest
	(*VerifyTokenResponse)(nil),        // 4: idm.VerifyTokenResponse
	(*RevokeTokenRequest)(nil),         // 5: idm.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),        // 6: idm.RevokeTokenResponse
	(*ObjectReference)(nil),            // 7: idm.ObjectReference
	(*SubjectReference)(nil),           // 8: idm.SubjectReference
	(*RelationshipTuple)(nil),          // 9: idm.RelationshipTuple
	(*CheckPermissionRequest)(nil),     // 10: idm.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),    // 11: idm.CheckPermissionResponse
	(*RelationshipUpdate)(nil),         // 12: idm.RelationshipUpdate
	(*WriteRelationshipsRequest)(nil),  // 13: idm.WriteRelationshipsRequest
	(*WriteRelationshipsResponse)(nil), // 14: idm.WriteRelationshipsResponse
	(*RelationshipFilter)(nil),         // 15: idm.RelationshipFilter
	(*ReadRelationshipsRequest)(nil),   // 16: idm.ReadRelationshipsRequest
	(*ReadRelationshipsResponse)(nil),  // 17: idm.ReadRelationshipsResponse
}
var file_proto_idm_proto_depIdxs = []int32{
	7,  // 0: idm.RelationshipTuple.resource:type_name -> idm.ObjectReference
	8,  // 1: idm.RelationshipTuple.subject:type_name -> idm.SubjectReference
	7,  // 2: idm.CheckPermissionRequest.resource:type_name -> idm.ObjectReference
	8,  // 3: idm.CheckPermissionRequest.subject:type_name -> idm.SubjectReference
	0,  // 4: idm.RelationshipUpdate.operation:type_name -> idm.RelationshipUpdateOperation
	9,  // 5: idm.RelationshipUpdate.relationship:type_name -> idm.RelationshipTuple
	12, // 6: idm.WriteRelationshipsRequest.updates:type_name -> idm.RelationshipUpdate
	7,  // 7: idm.RelationshipFilter.resource_filter:type_name -> idm.ObjectReference
	8,  // 8: idm.RelationshipFilter.subject_filter:type_name -> idm.SubjectReference
	15, // 9: idm.ReadRelationshipsRequest.filter:type_name -> idm.RelationshipFilter
	9,  // 10: idm.ReadRelationshipsResponse.relationships:type_name -> idm.RelationshipTuple
	1,  // 11: idm.IdentityService.Login:input_type -> idm.LoginRequest
	3,  // 12: idm.IdentityService.VerifyToken:input_type -> idm.VerifyTokenRequest
	5,  // 13: idm.IdentityService.RevokeToken:input_type -> idm.RevokeTokenRequest
	10, // 14: idm.IdentityService.CheckPermission:input_type -> idm.CheckPermissionRequest
	13, // 15: idm.IdentityService.WriteRelationships:input_type -> idm.WriteRelationshipsRequest
	16, // 16: idm.IdentityService.ReadRelationships:input_type -> idm.ReadRelationshipsRequest
	2,  // 17: idm.IdentityService.Login:output_type -> idm.LoginResponse
	4,  // 18: idm.IdentityService.VerifyToken:output_type -> idm.VerifyTokenResponse
	6,  // 19: idm.IdentityService.RevokeToken:output_type -> idm.RevokeTokenResponse
	11, // 20: idm.IdentityService.CheckPermission:output_type -> idm.CheckPermissionResponse
	14, // 21: idm.IdentityService.WriteRelationships:output_type -> idm.WriteRelationshipsResponse
	17, // 22: idm.IdentityService.ReadRelationships:output_type -> idm.ReadRelationshipsResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_idm_proto_init() }
func file_proto_idm_proto_init() {
	if File_proto_idm_proto != nil {
		return
	}
	file_proto_idm_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_idm_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_idm_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_idm_proto_rawDesc), len(file_proto_idm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_idm_proto_goTypes,
		DependencyIndexes: file_proto_idm_proto_depIdxs,
		EnumInfos:         file_proto_idm_proto_enumTypes,
		MessageInfos:      file_proto_idm_proto_msgTypes,
	}.Build()
	File_proto_idm_proto = out.File
	file_proto_idm_proto_goTypes = nil
	file_proto_idm_proto_depIdxs = nil
}
